In [ ]:
!pip install nbdt
!pip install pretrainedmodels

     |████████████████████████████████| 122kB 2.8MB/s 
     |████████████████████████████████| 440kB 8.5MB/s 
  Created wheel for nbdt: filename=nbdt-0.0.4-cp36-none-any.whl size=132323 sha256=d6ca93e530ac3299dd99d0cae7e245ea3a0309514ea1ca7ee3f420403802ee9a
  Stored in directory: /root/.cache/pip/wheels/24/42/99/f41adfed4f1250366d8add49449d06ca7583043684e3a3f4bd
Successfully built nbdt
     |████████████████████████████████| 61kB 1.8MB/s 
  Created wheel for pretrainedmodels: filename=pretrainedmodels-0.7.4-cp36-none-any.whl size=60964 sha256=c243c80d23c7d54afe909705bd7ae9320622cfd8d45815758a1d2c01fac14241
  Stored in directory: /root/.cache/pip/wheels/69/df/63/62583c096289713f22db605aa2334de5b591d59861a02c2ecd
Successfully built pretrainedmodels


In [ ]:
import torch.nn as nn
from nbdt.model import SoftNBDT
from nbdt.loss import SoftTreeSupLoss
from nbdt.hierarchy import generate_hierarchy
import pretrainedmodels
#model = pretrainedmodels.__dict__['fbresnet152'](num_classes=1000, pretrained='imagenet')

In [ ]:
# with open('./modelstate.txt', 'w') as fw:
#   fw.write(str(model.state_dict()))

In [ ]:
from nbdt.models import wrn28_10_cifar10
model1 = wrn28_10_cifar10(pretrained=True)
with open('./modelstate1.txt', 'w') as fw:
  fw.write(str(model1.state_dict()))

In [ ]:
from pytorchcv.models.wrn_cifar import wrn28_10_cifar10
model1 = wrn28_10_cifar10()
with open('./modelstate1.txt', 'w') as fw:
  fw.write(str(model1.state_dict()))

In [ ]:
fc = model1.state_dict()['output.weight'].squeeze()

In [ ]:
print(fc)

tensor([[-4.5172e-06, -1.6231e-12, -8.9549e-07,  ..., -9.2804e-02,
          1.4848e-04, -3.6705e-09],
        [-3.3804e-06, -1.4153e-12, -3.8851e-07,  ...,  4.6094e-01,
         -8.4855e-03, -1.8358e-09],
        [-9.5666e-07, -1.2534e-11,  8.6697e-07,  ..., -1.8066e-01,
          2.2463e-02,  1.4544e-08],
        ...,
        [ 2.9268e-05,  8.1077e-12,  3.4450e-08,  ..., -6.6081e-02,
         -4.9023e-02, -1.4758e-09],
        [-3.7178e-06,  1.3741e-10,  8.5237e-07,  ..., -6.5411e-02,
         -5.9429e-03,  2.8330e-10],
        [-6.1274e-06, -2.3807e-11,  6.3820e-07,  ..., -1.3238e-01,
         -6.8461e-04,  1.6061e-09]])


In [ ]:
fc = fc.detach()

In [ ]:
print(fc)

tensor([[-4.5172e-06, -1.6231e-12, -8.9549e-07,  ..., -9.2804e-02,
          1.4848e-04, -3.6705e-09],
        [-3.3804e-06, -1.4153e-12, -3.8851e-07,  ...,  4.6094e-01,
         -8.4855e-03, -1.8358e-09],
        [-9.5666e-07, -1.2534e-11,  8.6697e-07,  ..., -1.8066e-01,
          2.2463e-02,  1.4544e-08],
        ...,
        [ 2.9268e-05,  8.1077e-12,  3.4450e-08,  ..., -6.6081e-02,
         -4.9023e-02, -1.4758e-09],
        [-3.7178e-06,  1.3741e-10,  8.5237e-07,  ..., -6.5411e-02,
         -5.9429e-03,  2.8330e-10],
        [-6.1274e-06, -2.3807e-11,  6.3820e-07,  ..., -1.3238e-01,
         -6.8461e-04,  1.6061e-09]])


In [ ]:
from sklearn.cluster import AgglomerativeClustering

In [ ]:
clustering = AgglomerativeClustering(
        linkage='ward',
        n_clusters=2,
        affinity='euclidean',
    ).fit(fc)

In [ ]:
clustering.children_

array([[ 3,  5],
       [ 1,  9],
       [ 0,  8],
       [ 4,  7],
       [ 2,  6],
       [10, 14],
       [13, 15],
       [11, 12],
       [16, 17]])